"""Main voice-agent orchestration pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from voice_agent.llm import LLMClient
from voice_agent.rag import RAGPipeline
from voice_agent.stt import SpeechToText
from voice_agent.tts import TextToSpeech


@dataclass
class AgentResponse:
    """Structured response returned by :class:`VoiceAgent` for every turn."""

    transcript: str
    """What the caller said (output of STT)."""

    intent: str
    """Detected intent label."""

    reply_text: str
    """Text reply generated by the LLM."""

    reply_audio: bytes = field(default=b"", repr=False)
    """MP3 audio bytes of *reply_text* (empty when TTS is skipped)."""

    context_used: str = field(default="", repr=False)
    """RAG context passages that informed the reply."""


class VoiceAgent:
    """End-to-end voice agent: STT → intent → RAG → LLM → TTS.

    Example usage::

        agent = VoiceAgent()
        agent.load_knowledge_base()          # build / load FAISS index
        response = agent.handle_audio(audio_bytes)
        # response.reply_audio contains MP3 bytes ready to stream back

    For text-only usage (e.g., testing)::

        response = agent.handle_text("Where is my order?")
    """

    def __init__(
        self,
        stt: SpeechToText | None = None,
        tts: TextToSpeech | None = None,
        llm: LLMClient | None = None,
        rag: RAGPipeline | None = None,
    ) -> None:
        self.stt = stt or SpeechToText()
        self.tts = tts or TextToSpeech()
        self.llm = llm or LLMClient()
        self.rag = rag or RAGPipeline()

    # ------------------------------------------------------------------
    # Knowledge-base management
    # ------------------------------------------------------------------

    def load_knowledge_base(self, data_dir: str | None = None) -> None:
        """Build or load the FAISS vector index from knowledge-base files.

        If a saved index already exists on disk it is loaded; otherwise the
        documents in *data_dir* are embedded and the index is saved to disk.

        Args:
            data_dir: Directory containing ``.json`` / ``.txt`` knowledge-base
                      files.  Defaults to ``settings.data_dir``.
        """
        self.rag.load_or_build_index(data_dir)

    # ------------------------------------------------------------------
    # Main entry points
    # ------------------------------------------------------------------

    def handle_audio(
        self,
        audio_bytes: bytes,
        filename: str = "audio.wav",
        synthesize_reply: bool = True,
    ) -> AgentResponse:
        """Process a caller's audio clip end-to-end.

        1. Transcribe with STT (Whisper).
        2. Detect intent via LLM.
        3. Retrieve relevant context via RAG.
        4. Generate reply text via LLM.
        5. Optionally synthesize reply to audio via TTS.

        Args:
            audio_bytes: Raw audio bytes (wav / mp3 / m4a / …).
            filename: Filename hint for Whisper to infer format.
            synthesize_reply: Set to ``False`` to skip TTS (saves latency /
                              cost in batch/test scenarios).

        Returns:
            :class:`AgentResponse` with transcript, intent, reply text, and
            optionally reply audio bytes.
        """
        transcript = self.stt.transcribe(audio_bytes, filename=filename)
        return self._process(transcript, synthesize_reply=synthesize_reply)

    def handle_text(
        self,
        text: str,
        synthesize_reply: bool = False,
    ) -> AgentResponse:
        """Process a text query (bypasses STT).

        Useful for testing, chat interfaces, or hybrid text/voice deployments.

        Args:
            text: The caller's message in plain text.
            synthesize_reply: Set to ``True`` to include TTS audio in response.

        Returns:
            :class:`AgentResponse`.
        """
        return self._process(text, synthesize_reply=synthesize_reply)

    # ------------------------------------------------------------------
    # Internal pipeline
    # ------------------------------------------------------------------

    def _process(self, transcript: str, synthesize_reply: bool) -> AgentResponse:
        intent = self.llm.detect_intent(transcript)
        context = self.rag.get_context(transcript)
        reply_text = self.llm.generate_response(transcript, context)

        reply_audio = b""
        if synthesize_reply:
            reply_audio = self.tts.synthesize(reply_text)

        return AgentResponse(
            transcript=transcript,
            intent=intent,
            reply_text=reply_text,
            reply_audio=reply_audio,
            context_used=context,
        )
